service: signage-auth

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  memorySize: 512
  timeout: 60
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ecs:*
        - iam:PassRole
      Resource: "*"

resources:
  Resources:
    EcsServiceAuth:
      Type: AWS::ECS::Service
      DependsOn:
        - PathBasedRoutingRuleAuth
      Properties:
        TaskDefinition: !Ref TaskDefinitionAuth
        # Cluster: !ImportValue signage-service-${self:provider.stage}-ECSClusterArn
        Cluster: !ImportValue signage-service-${self:provider.stage}-ECSClusterArn
        LaunchType: FARGATE
        DesiredCount: 1
        EnableExecuteCommand: true
        DeploymentConfiguration:
          MaximumPercent: 200
          MinimumHealthyPercent: 70
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIP: ENABLED
            Subnets:
              - subnet-0694073f03cdc80a7
              - subnet-003f960384c510393
              - subnet-097a00a19d8b07d73
            SecurityGroups:
              - sg-0d982615fe1d11784
        LoadBalancers:
          - ContainerName: "${self:service}-${self:provider.stage}"
            ContainerPort: 9090
            TargetGroupArn: !Ref TargetGroupAuth

    TaskDefinitionAuth:
      Type: AWS::ECS::TaskDefinition
      Properties:
        Family: "${self:service}"
        Cpu: 512
        Memory: 1024
        NetworkMode: awsvpc
        RequiresCompatibilities:
          - FARGATE
        ExecutionRoleArn: !ImportValue signage-service-${self:provider.stage}-ECSTaskExecutionRoleArn
        TaskRoleArn: !ImportValue signage-service-${self:provider.stage}-ECSTaskRoleArn
        ContainerDefinitions:
          - Name: "${self:service}-${self:provider.stage}"
            Image: 180294218712.dkr.ecr.us-east-1.amazonaws.com/api-two:v${env:VERSION}
            PortMappings:
              - ContainerPort: 9090
                HostPort: 9090
                Protocol: tcp
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: "${self:service}"
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: "${self:service}"

    TargetGroupAuth:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        VpcId: "vpc-0aba4745bbae42ebd"
        Port: 9090
        Protocol: HTTP
        Matcher:
          HttpCode: "200-499"
        HealthCheckIntervalSeconds: 30
        HealthCheckPath: "/"
        HealthCheckProtocol: "HTTP"
        HealthCheckTimeoutSeconds: 5
        HealthyThresholdCount: 10
        Name: "${self:service}-tg"
        TargetType: ip
  
    LoadBalancerListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        LoadBalancerArn: !ImportValue signage-service-${self:provider.stage}-ApplicationLoadBalancerArn
        Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupArn: !Ref TargetGroupAuth
    PathBasedRoutingRuleAuth:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        Actions:
          - Type: forward
            TargetGroupArn: !Ref TargetGroupAuth
        Conditions:
          - Field: path-pattern
            Values:
              - /auth
              - /auth/*
        # ListenerArn: !ImportValue signage-service-${self:provider.stage}-LoadBalancerListener
        # Priority: 2
        ListenerArn: !Ref LoadBalancerListener
        Priority: 1

    CloudWatchLogsGroupAuth:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: "${self:service}"
        RetentionInDays: 30
    
